### ISSUE TITLE
Cannot save.

### ISSUE THREAD

**Issue by jnphilipp** [Transkribus/TWI-edit#6]
In `Correction Interface, Line by Line` clicking Save changes results in an javascript error message 500.

On the command line the output is:
```
[29/May/2017 12:44:32] - ERROR - exception : Internal Server Error: /edit/correct/6258/19682/1
Traceback (most recent call last):
  File "/home/jnphilipp/Documents/Programmierung/projekte/read/TWI-mc/.venv/lib/python3.5/site-packages/django/core/handlers/exception.py", line 39, in inner
    response = get_response(request)
  File "/home/jnphilipp/Documents/Programmierung/projekte/read/TWI-mc/.venv/lib/python3.5/site-packages/django/core/handlers/base.py", line 249, in _legacy_get_response
    response = self._get_response(request)
  File "/home/jnphilipp/Documents/Programmierung/projekte/read/TWI-mc/.venv/lib/python3.5/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/jnphilipp/Documents/Programmierung/projekte/read/TWI-mc/.venv/lib/python3.5/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/jnphilipp/Documents/Programmierung/projekte/read/TWI-mc/.venv/lib/python3.5/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/home/jnphilipp/Documents/Programmierung/projekte/read/TWI-mc/apps/edit/views.py", line 130, in correct
    t_save_transcript(request, ElementTree.tostring(transcript_root), collId, docId, page)
NameError: name 't_save_transcript' is not defined
[29/May/2017 12:44:32] - ERROR - basehttp : "POST /edit/correct/6258/19682/1 HTTP/1.1" 500 20840
```

**Comment by kansallisarkisto** [comment]
Fixed (t_save_transcript -> t.save_transcript).
